import { Category, Service, User, Booking, Review, AppNotification, Address, Coupon } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-cleaning',
    name: 'Home Cleaning',
    slug: 'cleaning',
    icon: 'sparkles',
    description: 'Deep cleaning, kitchen, bathroom, and sofa sanitization',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80',
    color: '#3B82F6',
    servicesCount: 4,
  },
  {
    id: 'cat-plumbing',
    name: 'Plumbing',
    slug: 'plumbing',
    icon: 'water',
    description: 'Pipe leaks, taps, drainage, and water heater repairs',
    imageUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&auto=format&fit=crop&q=80',
    color: '#0284C7',
    servicesCount: 3,
  },
  {
    id: 'cat-electrical',
    name: 'Electrical',
    slug: 'electrical',
    icon: 'flash',
    description: 'Wiring, switches, chandeliers, and circuit breaker fixes',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
    color: '#D97706',
    servicesCount: 3,
  },
  {
    id: 'cat-ac-repair',
    name: 'AC & Appliances',
    slug: 'ac-repair',
    icon: 'snow',
    description: 'AC servicing, gas refills, washing machines, and refrigerators',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    color: '#0891B2',
    servicesCount: 3,
  },
  {
    id: 'cat-painting',
    name: 'Painting',
    slug: 'painting',
    icon: 'color-palette',
    description: 'Interior wall painting, touch-ups, and waterproofing',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&auto=format&fit=crop&q=80',
    color: '#DB2777',
    servicesCount: 2,
  },
  {
    id: 'cat-carpentry',
    name: 'Carpentry',
    slug: 'carpentry',
    icon: 'hammer',
    description: 'Furniture assembly, door lock repairs, and custom woodwork',
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&auto=format&fit=crop&q=80',
    color: '#7C3AED',
    servicesCount: 2,
  },
  {
    id: 'cat-moving',
    name: 'Moving & Packing',
    slug: 'moving',
    icon: 'cube',
    description: 'Home relocation, heavy luggage transport, and unpacking',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
    color: '#059669',
    servicesCount: 2,
  },
  {
    id: 'cat-pest',
    name: 'Pest Control',
    slug: 'pest-control',
    icon: 'shield-checkmark',
    description: 'Termite treatment, bed bug control, and general fumigation',
    imageUrl: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=600&auto=format&fit=crop&q=80',
    color: '#0D9488',
    servicesCount: 2,
  },
];

export const INITIAL_PROVIDERS: User[] = [
  {
    id: 'prov-1',
    email: 'david.electric@fixora.com',
    name: 'David Miller',
    phone: '+1 (555) 234-5678',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bio: 'Licensed Master Electrician with 9+ years experience in domestic wiring, smart home installations, and safety inspections.',
    address: 'Downtown, Sector 4',
    hourlyRate: 45,
    rating: 4.9,
    reviewsCount: 128,
    isVerified: true,
    availabilityStatus: 'available',
    earnings: 3420,
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'prov-2',
    email: 'sarah.plumbing@fixora.com',
    name: 'Sarah Jenkins',
    phone: '+1 (555) 345-6789',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    bio: 'Certified plumbing technician specializing in high-pressure leak detection, tap overhauls, and drainage clearing.',
    address: 'Westbrook Avenue',
    hourlyRate: 50,
    rating: 4.8,
    reviewsCount: 94,
    isVerified: true,
    availabilityStatus: 'available',
    earnings: 2850,
    createdAt: '2025-02-10T10:00:00Z',
  },
  {
    id: 'prov-3',
    email: 'cleaners.apex@fixora.com',
    name: 'Apex Clean Pro',
    phone: '+1 (555) 456-7890',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    bio: 'Eco-friendly deep cleaning specialists with hospital-grade sanitization technology for residences and villas.',
    address: 'Metro Heights 12',
    hourlyRate: 35,
    rating: 4.9,
    reviewsCount: 215,
    isVerified: true,
    availabilityStatus: 'available',
    earnings: 5210,
    createdAt: '2024-11-01T12:00:00Z',
  },
  {
    id: 'prov-4',
    email: 'marcus.wood@fixora.com',
    name: 'Marcus Vance',
    phone: '+1 (555) 567-8901',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: 'Custom carpentry, modular furniture assembly (IKEA expert), and architectural door hardware replacement.',
    address: 'Oakridge Boulevard',
    hourlyRate: 40,
    rating: 4.7,
    reviewsCount: 62,
    isVerified: true,
    availabilityStatus: 'busy',
    earnings: 1980,
    createdAt: '2025-03-05T09:00:00Z',
  },
  {
    id: 'prov-5',
    email: 'elena.paint@fixora.com',
    name: 'Elena Rostova',
    phone: '+1 (555) 678-9012',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    bio: 'Professional color consultant and painting specialist. Odorless paint options, dust-free prep, and 3-year warranty.',
    address: 'Hilltop View',
    hourlyRate: 55,
    rating: 5.0,
    reviewsCount: 48,
    isVerified: true,
    availabilityStatus: 'available',
    earnings: 2600,
    createdAt: '2025-02-22T14:00:00Z',
  },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv-clean-deep',
    providerId: 'prov-3',
    providerName: 'Apex Clean Pro',
    providerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.9,
    categoryId: 'cat-cleaning',
    categoryName: 'Home Cleaning',
    title: 'Full Home Deep Cleaning',
    description: 'Thorough top-to-bottom scrub and sanitization of bedrooms, living room, balcony, kitchen degreasing, and bathrooms.',
    price: 89,
    originalPrice: 120,
    duration: '3-4 hours',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 154,
    isPopular: true,
    isActive: true,
    features: ['Eco-friendly cleaning agents', 'High-pressure vacuuming', 'Bathroom grout cleaning', 'Window track sanitizing'],
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'srv-clean-sofa',
    providerId: 'prov-3',
    providerName: 'Apex Clean Pro',
    providerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.9,
    categoryId: 'cat-cleaning',
    categoryName: 'Home Cleaning',
    title: 'Sofa & Fabric Upholstery Shampooing',
    description: 'Deep extraction cleaning for fabric and leather sofas. Removes stubborn coffee/pet stains and dust mites.',
    price: 49,
    originalPrice: 65,
    duration: '1-2 hours',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 61,
    isPopular: false,
    isActive: true,
    features: ['Hot water extraction', 'Quick dry formula (3-4 hrs)', 'Fabric conditioning', 'Odor neutralizer'],
    createdAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'srv-plumb-leak',
    providerId: 'prov-2',
    providerName: 'Sarah Jenkins',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.8,
    categoryId: 'cat-plumbing',
    categoryName: 'Plumbing',
    title: 'Leak Repair & Pipe Replacement',
    description: 'Rapid inspection and fix for dripping faucets, bursting pipes, under-sink leaks, and loose connections.',
    price: 45,
    originalPrice: 55,
    duration: '45-60 mins',
    imageUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 52,
    isPopular: true,
    isActive: true,
    features: ['Pressure test diagnostics', 'O-ring & washer replacement', '30-day rework warranty', 'Clean-up after repair'],
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'srv-plumb-drain',
    providerId: 'prov-2',
    providerName: 'Sarah Jenkins',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.8,
    categoryId: 'cat-plumbing',
    categoryName: 'Plumbing',
    title: 'Complete Drain Unclogging',
    description: 'Heavy duty motorized snake auger clearing for backed-up kitchen sinks, bathroom floor drains, and sewer lines.',
    price: 55,
    duration: '1 hour',
    imageUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 42,
    isPopular: false,
    isActive: true,
    features: ['High-torque drain snake', 'Bio-enzyme pipe wash', 'No harsh damaging acid', 'Guaranteed free flow'],
    createdAt: '2025-01-12T00:00:00Z',
  },
  {
    id: 'srv-elec-install',
    providerId: 'prov-1',
    providerName: 'David Miller',
    providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.9,
    categoryId: 'cat-electrical',
    categoryName: 'Electrical',
    title: 'Ceiling Fan & Chandelier Fitting',
    description: 'Safe mounting and wiring of heavy chandeliers, decorative lighting, exhaust fans, and modern ceiling fans.',
    price: 39,
    originalPrice: 50,
    duration: '1 hour',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 88,
    isPopular: true,
    isActive: true,
    features: ['Stud beam safety anchoring', 'Balance calibration', 'Smart switch integration', 'Voltage surge testing'],
    createdAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'srv-elec-switch',
    providerId: 'prov-1',
    providerName: 'David Miller',
    providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.9,
    categoryId: 'cat-electrical',
    categoryName: 'Electrical',
    title: 'MCB & Circuit Breaker Overhaul',
    description: 'Diagnostics for frequent tripping, burnt sockets, switchboard replacements, and grounding/earthing check.',
    price: 65,
    duration: '1-2 hours',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 40,
    isPopular: false,
    isActive: true,
    features: ['Thermal overload test', 'Fire-resistant wiring', 'Earthing check', 'Safety certificate'],
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'srv-ac-servicing',
    providerId: 'prov-1',
    providerName: 'David Miller',
    providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.9,
    categoryId: 'cat-ac-repair',
    categoryName: 'AC & Appliances',
    title: 'Split AC Deep Foam Jet Servicing',
    description: 'High-pressure foam jet wash for cooling coils, filter cleaning, refrigerant pressure check, and drain tray flush.',
    price: 59,
    originalPrice: 80,
    duration: '1-2 hours',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 97,
    isPopular: true,
    isActive: true,
    features: ['2x faster cooling restore', 'Gas leak detection', 'Power consumption audit', 'Antibacterial foam'],
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'srv-carp-furniture',
    providerId: 'prov-4',
    providerName: 'Marcus Vance',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.7,
    categoryId: 'cat-carpentry',
    categoryName: 'Carpentry',
    title: 'Modular Furniture & Bed Assembly',
    description: 'Expert assembly of flat-pack furniture (IKEA, Wayfair, Target) including bed frames, wardrobes, and TV cabinets.',
    price: 50,
    duration: '2 hours',
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 39,
    isPopular: false,
    isActive: true,
    features: ['Wall anti-tip anchoring', 'Zero surface scratches', 'All toolsets provided', 'Packaging debris clearance'],
    createdAt: '2025-02-15T00:00:00Z',
  },
  {
    id: 'srv-paint-accent',
    providerId: 'prov-5',
    providerName: 'Elena Rostova',
    providerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    providerRating: 5.0,
    categoryId: 'cat-painting',
    categoryName: 'Painting',
    title: 'Accent Wall & Room Painting',
    description: 'Flawless double-coat painting with premium low-VOC paint. Includes putty plastering, masking tape, and cleanup.',
    price: 110,
    originalPrice: 140,
    duration: '1 day',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 32,
    isPopular: true,
    isActive: true,
    features: ['Furniture masking protection', 'Color tone matching', 'Zero odor paint', 'Smooth satin finish'],
    createdAt: '2025-02-25T00:00:00Z',
  },
  {
    id: 'srv-move-local',
    providerId: 'prov-4',
    providerName: 'Marcus Vance',
    providerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    providerRating: 4.7,
    categoryId: 'cat-moving',
    categoryName: 'Moving & Packing',
    title: 'Studio / 1-BHK Local Moving Assist',
    description: 'Professional movers with blankets, stretch wrap, and dollies to safely pack, load, and relocate your home.',
    price: 135,
    duration: '3-4 hours',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 23,
    isPopular: false,
    isActive: true,
    features: ['Heavy furniture dollies', 'Protective bubble wrap', 'Elevator & stair handling', 'Damage-free guarantee'],
    createdAt: '2025-03-01T00:00:00Z',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book-101',
    customerId: 'cust-demo',
    customerName: 'Alex Morgan',
    customerPhone: '+1 (555) 987-6543',
    customerEmail: 'alex.morgan@example.com',
    providerId: 'prov-3',
    providerName: 'Apex Clean Pro',
    providerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    providerPhone: '+1 (555) 456-7890',
    serviceId: 'srv-clean-deep',
    serviceTitle: 'Full Home Deep Cleaning',
    categoryName: 'Home Cleaning',
    serviceImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80',
    totalPrice: 89,
    date: '2026-10-08',
    timeSlot: '10:00 AM - 12:00 PM',
    address: {
      id: 'addr-1',
      label: 'Home',
      street: '742 Evergreen Terrace',
      apartment: 'Apt 4B',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62704',
      isDefault: true,
    },
    notes: 'Please focus especially on the kitchen exhaust hood and balcony windows.',
    status: 'in_progress',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    createdAt: '2026-10-05T14:20:00Z',
    updatedAt: '2026-10-06T09:15:00Z',
  },
  {
    id: 'book-102',
    customerId: 'cust-demo',
    customerName: 'Alex Morgan',
    customerPhone: '+1 (555) 987-6543',
    customerEmail: 'alex.morgan@example.com',
    providerId: 'prov-1',
    providerName: 'David Miller',
    providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    providerPhone: '+1 (555) 234-5678',
    serviceId: 'srv-ac-servicing',
    serviceTitle: 'Split AC Deep Foam Jet Servicing',
    categoryName: 'AC & Appliances',
    serviceImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    totalPrice: 59,
    date: '2026-10-10',
    timeSlot: '02:00 PM - 04:00 PM',
    address: {
      id: 'addr-1',
      label: 'Home',
      street: '742 Evergreen Terrace',
      apartment: 'Apt 4B',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62704',
      isDefault: true,
    },
    notes: 'Living room AC has low cooling airflow.',
    status: 'accepted',
    paymentStatus: 'unpaid',
    paymentMethod: 'cash',
    createdAt: '2026-10-04T11:00:00Z',
    updatedAt: '2026-10-04T12:30:00Z',
  },
  {
    id: 'book-103',
    customerId: 'cust-demo',
    customerName: 'Alex Morgan',
    customerPhone: '+1 (555) 987-6543',
    customerEmail: 'alex.morgan@example.com',
    providerId: 'prov-2',
    providerName: 'Sarah Jenkins',
    providerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    providerPhone: '+1 (555) 345-6789',
    serviceId: 'srv-plumb-leak',
    serviceTitle: 'Leak Repair & Pipe Replacement',
    categoryName: 'Plumbing',
    serviceImage: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&auto=format&fit=crop&q=80',
    totalPrice: 45,
    date: '2026-09-28',
    timeSlot: '11:00 AM - 01:00 PM',
    address: {
      id: 'addr-1',
      label: 'Home',
      street: '742 Evergreen Terrace',
      apartment: 'Apt 4B',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62704',
      isDefault: true,
    },
    notes: 'Fixed bathroom sink pipe.',
    status: 'completed',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    createdAt: '2026-09-27T08:10:00Z',
    updatedAt: '2026-09-28T12:55:00Z',
  },
  {
    id: 'book-104',
    customerId: 'cust-2',
    customerName: 'Jessica Taylor',
    customerPhone: '+1 (555) 888-9999',
    customerEmail: 'jessica.t@example.com',
    providerId: 'prov-1',
    providerName: 'David Miller',
    providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    serviceId: 'srv-elec-install',
    serviceTitle: 'Ceiling Fan & Chandelier Fitting',
    categoryName: 'Electrical',
    serviceImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
    totalPrice: 39,
    date: '2026-10-07',
    timeSlot: '04:00 PM - 06:00 PM',
    address: {
      id: 'addr-2',
      label: 'Home',
      street: '124 Conch Street',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62701',
    },
    status: 'pending',
    paymentStatus: 'unpaid',
    paymentMethod: 'cash',
    createdAt: '2026-10-06T08:00:00Z',
    updatedAt: '2026-10-06T08:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    bookingId: 'book-103',
    serviceId: 'srv-plumb-leak',
    serviceTitle: 'Leak Repair & Pipe Replacement',
    providerId: 'prov-2',
    customerId: 'cust-demo',
    customerName: 'Alex Morgan',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Sarah arrived right on time and had all the right replacement parts in her van! The leak under the kitchen sink was resolved in 30 minutes. Super clean and polite.',
    createdAt: '2026-09-28T13:30:00Z',
  },
  {
    id: 'rev-2',
    bookingId: 'book-99',
    serviceId: 'srv-clean-deep',
    serviceTitle: 'Full Home Deep Cleaning',
    providerId: 'prov-3',
    customerId: 'cust-3',
    customerName: 'Robert Vance',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Spectacular deep clean! The bathroom tiles look brand new, and they managed to remove kitchen oil grime that had resisted everything I tried. Definitely booking Apex again.',
    createdAt: '2026-09-24T18:00:00Z',
  },
  {
    id: 'rev-3',
    bookingId: 'book-98',
    serviceId: 'srv-elec-install',
    serviceTitle: 'Ceiling Fan & Chandelier Fitting',
    providerId: 'prov-1',
    customerId: 'cust-4',
    customerName: 'Emma Watson',
    customerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&auto=format&fit=crop&q=80',
    rating: 4.8,
    comment: 'David installed our 15kg dining room chandelier with heavy-duty anchors. Very safe, explained the switch circuit diagram, and checked all dimming functionality.',
    createdAt: '2026-09-20T16:45:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'cust-demo',
    title: 'Booking Confirmed! 🎉',
    message: 'David Miller confirmed your AC Servicing booking for Oct 10 at 02:00 PM.',
    type: 'booking',
    read: false,
    createdAt: '2026-10-04T12:30:00Z',
    bookingId: 'book-102',
  },
  {
    id: 'notif-2',
    userId: 'cust-demo',
    title: 'Provider is In Progress 🧰',
    message: 'Apex Clean Pro has started work on your Full Home Deep Cleaning.',
    type: 'booking',
    read: false,
    createdAt: '2026-10-06T09:15:00Z',
    bookingId: 'book-101',
  },
  {
    id: 'notif-3',
    userId: 'cust-demo',
    title: 'Special 20% Off Weekend Promo 🎁',
    message: 'Use code FIXORA20 on any Plumbing or Painting service this weekend!',
    type: 'promo',
    read: true,
    createdAt: '2026-10-03T08:00:00Z',
  },
];

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    userId: 'cust-demo',
    label: 'Home',
    street: '742 Evergreen Terrace',
    apartment: 'Apt 4B',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62704',
    isDefault: true,
  },
  {
    id: 'addr-2',
    userId: 'cust-demo',
    label: 'Work',
    street: '100 Innovation Way',
    apartment: 'Floor 3, Suite 300',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62701',
    isDefault: false,
  },
];

export const INITIAL_CHAT_MESSAGES: Record<string, any[]> = {
  'book-101': [
    {
      id: 'msg-1',
      bookingId: 'book-101',
      senderId: 'prov-3',
      senderName: 'Apex Clean Pro',
      senderRole: 'provider',
      recipientId: 'cust-demo',
      text: 'Hello Alex! Our team of 2 cleaners is currently on the way with steam equipment. We should reach by 09:50 AM.',
      timestamp: '2026-10-06T09:30:00Z',
      isRead: true,
    },
    {
      id: 'msg-2',
      bookingId: 'book-101',
      senderId: 'cust-demo',
      senderName: 'Alex Morgan',
      senderRole: 'customer',
      recipientId: 'prov-3',
      text: 'Great! The gate code is #4821 and lift is working normally.',
      timestamp: '2026-10-06T09:32:00Z',
      isRead: true,
    },
    {
      id: 'msg-3',
      bookingId: 'book-101',
      senderId: 'prov-3',
      senderName: 'Apex Clean Pro',
      senderRole: 'provider',
      recipientId: 'cust-demo',
      text: 'Perfect, we have arrived and started with the master bedroom and living room.',
      timestamp: '2026-10-06T09:55:00Z',
      isRead: true,
    },
  ],
};

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'cpn-1',
    code: 'FIXORA20',
    discountPercent: 20,
    minOrderAmount: 40,
    description: '20% OFF on all home cleaning, plumbing and repair services',
    expiryDate: '2026-12-31',
    isActive: true,
    usageCount: 142,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cpn-2',
    code: 'WELCOME10',
    discountPercent: 10,
    minOrderAmount: 25,
    description: '10% OFF for all first-time bookings on Fixora',
    expiryDate: '2026-11-30',
    isActive: true,
    usageCount: 89,
    createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cpn-3',
    code: 'SUMMER15',
    discountPercent: 15,
    minOrderAmount: 50,
    description: '15% Summer special on AC repair & painting',
    expiryDate: '2026-10-31',
    isActive: true,
    usageCount: 65,
    createdAt: '2026-03-01T00:00:00Z',
  },
];

